spring:
  datasource:
    url: jdbc:postgresql://database:5432/currency_exchange
    username: currency
    password: password
  jpa:
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.PostgreSQLDialect